services:
  med_rda:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: med_rda_fullstack
    env_file:
      - .env
    ports:
      - "8086:8086"
    volumes:
      - ./database:/app/database
    restart: unless-stopped
